In [6]:
import numpy as np
import pandas as pd
from scipy import misc

In [7]:
path = "../NetDissect-Lite/dataset/broden1_224/"


In [8]:
index = pd.read_csv(path + "index.csv")
label = pd.read_csv(path + "label.csv")
category = pd.read_csv(path + "category.csv")

In [9]:
index.sample(5)

image  split   ih   iw   sh   sw  \
14955    ade20k/ADE_val_00001771.jpg  train  224  224  112  112   
11372         pascal/2009_000962.jpg  train  224  224  112  112   
27479  ade20k/ADE_train_00016961.jpg  train  224  224  112  112   
17704  ade20k/ADE_train_00001875.jpg  train  224  224  112  112   
7632          opensurfaces/22742.jpg  train  224  224  112  112   

                                     color  \
14955    ade20k/ADE_val_00001771_color.png   
11372         pascal/2009_000962_color.png   
27479  ade20k/ADE_train_00016961_color.png   
17704  ade20k/ADE_train_00001875_color.png   
7632          opensurfaces/22742_color.png   

                                     object  \
14955    ade20k/ADE_val_00001771_object.png   
11372         pascal/2009_000962_object.png   
27479  ade20k/ADE_train_00016961_object.png   
17704  ade20k/ADE_train_00001875_object.png   
7632                                    NaN   

                                                    part  \
14955                 ade20k/ADE_val_00001771_part_1.png   
11372                        pascal/2009_000962_part.png   
27479  ade20k/ADE_train_00016961_part_1.png;ade20k/AD...   
17704                                                NaN   
7632                                                 NaN   

                              material  scene texture  
14955                              NaN    0.0     NaN  
11372                              NaN    NaN     NaN  
27479                              NaN   59.0     NaN  
17704                              NaN  772.0     NaN  
7632   opensurfaces/22742_material.png    NaN     NaN

In [10]:
index_train = index[index["split"]== "train"]
index_train.head(10)

image  split   ih   iw   sh   sw  \
0         opensurfaces/25605.jpg  train  224  224  112  112   
1         opensurfaces/24183.jpg  train  224  224  112  112   
2         opensurfaces/72705.jpg  train  224  224  112  112   
3        opensurfaces/100509.jpg  train  224  224  112  112   
4  ade20k/ADE_train_00003891.jpg  train  224  224  112  112   
5         opensurfaces/97035.jpg  train  224  224  112  112   
6  ade20k/ADE_train_00006107.jpg  train  224  224  112  112   
7         opensurfaces/20360.jpg  train  224  224  112  112   
8          opensurfaces/6582.jpg  train  224  224  112  112   
9         opensurfaces/97767.jpg  train  224  224  112  112   

                                 color                                object  \
0         opensurfaces/25605_color.png                                   NaN   
1         opensurfaces/24183_color.png                                   NaN   
2         opensurfaces/72705_color.png                                   NaN   
3        opensurfaces/100509_color.png                                   NaN   
4  ade20k/ADE_train_00003891_color.png  ade20k/ADE_train_00003891_object.png   
5         opensurfaces/97035_color.png                                   NaN   
6  ade20k/ADE_train_00006107_color.png  ade20k/ADE_train_00006107_object.png   
7         opensurfaces/20360_color.png                                   NaN   
8          opensurfaces/6582_color.png                                   NaN   
9         opensurfaces/97767_color.png                                   NaN   

                                   part                          material  \
0                                   NaN   opensurfaces/25605_material.png   
1                                   NaN   opensurfaces/24183_material.png   
2                                   NaN   opensurfaces/72705_material.png   
3                                   NaN  opensurfaces/100509_material.png   
4                                   NaN                               NaN   
5                                   NaN   opensurfaces/97035_material.png   
6  ade20k/ADE_train_00006107_part_1.png                               NaN   
7                                   NaN   opensurfaces/20360_material.png   
8                                   NaN    opensurfaces/6582_material.png   
9                                   NaN   opensurfaces/97767_material.png   

   scene texture  
0    NaN     NaN  
1    NaN     NaN  
2    NaN     NaN  
3    NaN     NaN  
4   83.0     NaN  
5    NaN     NaN  
6  301.0     NaN  
7    NaN     NaN  
8    NaN     NaN  
9    NaN     NaN

In [11]:
## Let's isolate just images with segmented objects 

objects_only = index[index["object"].notnull()][["image", "split", "ih", "iw", "sh", "sw", "color", "object"]]

## let's count the number of objects in each image
objects_only["object_count"] = objects_only["object"].apply(lambda x: len(x.split(";")))

objects_only.sort_values("object_count", ascending = True)

objects_only.head(10)

## So it seems like the images (despite the descriptions of the data) only have one object each.

image  split   ih   iw   sh   sw  \
4   ade20k/ADE_train_00003891.jpg  train  224  224  112  112   
6   ade20k/ADE_train_00006107.jpg  train  224  224  112  112   
12  ade20k/ADE_train_00010928.jpg  train  224  224  112  112   
17         pascal/2010_004760.jpg  train  224  224  112  112   
18  ade20k/ADE_train_00018550.jpg  train  224  224  112  112   
21  ade20k/ADE_train_00019640.jpg  train  224  224  112  112   
23  ade20k/ADE_train_00017062.jpg  train  224  224  112  112   
24  ade20k/ADE_train_00001215.jpg  train  224  224  112  112   
26  ade20k/ADE_train_00011520.jpg  train  224  224  112  112   
29  ade20k/ADE_train_00015917.jpg  train  224  224  112  112   

                                  color                                object  \
4   ade20k/ADE_train_00003891_color.png  ade20k/ADE_train_00003891_object.png   
6   ade20k/ADE_train_00006107_color.png  ade20k/ADE_train_00006107_object.png   
12  ade20k/ADE_train_00010928_color.png  ade20k/ADE_train_00010928_object.png   
17         pascal/2010_004760_color.png         pascal/2010_004760_object.png   
18  ade20k/ADE_train_00018550_color.png  ade20k/ADE_train_00018550_object.png   
21  ade20k/ADE_train_00019640_color.png  ade20k/ADE_train_00019640_object.png   
23  ade20k/ADE_train_00017062_color.png  ade20k/ADE_train_00017062_object.png   
24  ade20k/ADE_train_00001215_color.png  ade20k/ADE_train_00001215_object.png   
26  ade20k/ADE_train_00011520_color.png  ade20k/ADE_train_00011520_object.png   
29  ade20k/ADE_train_00015917_color.png  ade20k/ADE_train_00015917_object.png   

    object_count  
4              1  
6              1  
12             1  
17             1  
18             1  
21             1  
23             1  
24             1  
26             1  
29             1

In [12]:
label.shape
label.head()

number     name      category  frequency      coverage syns
0       1  black-c  color(62358)      62358  11135.320474  NaN
1       2   grey-c  color(62310)      62310  12712.843129  NaN
2       3  white-c  color(62054)      62054   5778.038204  NaN
3       4  brown-c  color(61583)      61583  14549.652454  NaN
4       5  green-c  color(61508)      61508   5049.989735  NaN

In [37]:
category.head(6) # there are only 6 categories

name  first  last  count  frequency
0     color      1    11     11     651776
1    object     12  1197    584     271047
2      part     12  1186    234     132414
3  material     13   891     32      54511
4     scene     59  1179    468      17746
5   texture    237   391     47       6611

In [31]:
## We want to produce three sets of data of different sizes

In [63]:
image = misc.imread(path + "images/" + "ade20k/ADE_train_00003891_color.png")
print (image)

[[[ 4  0  0]
  [ 4  0  0]
  [ 4  0  0]
  ..., 
  [ 6  0  0]
  [ 6  0  0]
  [ 0  0  0]]

 [[ 4  0  0]
  [ 4  0  0]
  [ 4  0  0]
  ..., 
  [ 4  0  0]
  [ 4  0  0]
  [ 0  0  0]]

 [[ 4  0  0]
  [ 4  0  0]
  [ 4  0  0]
  ..., 
  [ 4  0  0]
  [ 4  0  0]
  [ 0  0  0]]

 ..., 
 [[ 4  0  0]
  [11  0  0]
  [10  0  0]
  ..., 
  [11  0  0]
  [11  0  0]
  [ 0  0  0]]

 [[11  0  0]
  [10  0  0]
  [11  0  0]
  ..., 
  [ 4  0  0]
  [ 4  0  0]
  [ 0  0  0]]

 [[11  0  0]
  [10  0  0]
  [10  0  0]
  ..., 
  [ 4  0  0]
  [ 4  0  0]
  [ 0  0  0]]]


In [ ]:
## 